version: '3.8'

services:
  # Backend API service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=bandmate_dev
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret_key
      - JWT_EXPIRES_IN=24h
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  # Database service
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bandmate_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
